# Generated by Django 5.2.14 on 2026-05-15 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='issue',
            name='address',
            field=models.CharField(blank=True, help_text='Street address of the issue location', max_length=255),
        ),
        migrations.AddField(
            model_name='issue',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Authority assigned to this issue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('road', 'Road Damage'), ('sanitation', 'Sanitation'), ('electricity', 'Electricity'), ('water', 'Water Supply'), ('other', 'Other')], default='other', help_text='Category of the issue', max_length=50),
        ),
        migrations.AlterField(
            model_name='issue',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who reported this issue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(help_text='Detailed description of the issue'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='image',
            field=models.ImageField(blank=True, help_text='Image evidence of the issue', null=True, upload_to='issues/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='latitude',
            field=models.FloatField(help_text='Geographic latitude'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='longitude',
            field=models.FloatField(help_text='Geographic longitude'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', help_text='Current status of the issue', max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(help_text='Brief title of the issue', max_length=255),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['status', '-created_at'], name='issues_issu_status_6ee1cb_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['category', 'status'], name='issues_issu_categor_cf150f_idx'),
        ),
    ]
