# Generated by Django 5.2.14 on 2026-05-15 16:19

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('authority', 'Authority'), ('admin', 'Admin'), ('ngo', 'NGO / Organisation')], default='citizen', help_text='User role in the UrbanTrace system', max_length=20),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('registration_id', models.CharField(max_length=100)),
                ('focus_area', models.CharField(choices=[('civic', 'Civic Rights'), ('environment', 'Environment'), ('infrastructure', 'Infrastructure'), ('welfare', 'Welfare')], default='civic', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
